<nav class="navbar navbar-default navbar-fixed-top"" role="navigation">
<div class="container ">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
<!--            <img src="--><?php ///*echo $this->basePath('img/zf2-logo.png')  */?><!--" alt="Zend Framework 2"/>-->
            &nbsp;<< <?php echo $this->translate('Blog') ?> >></a>
    </div>
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">

            <?php foreach ($this->container as $page) { ?>
                <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
                <?php // when using partials we need to manually check for ACL conditions ?>
                <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) { continue; } ?>
                <?php $hasChildren = $page->hasPages(); ?>
                <?php if (!$hasChildren) { ?>
                    <li class="<?=($page->getActive())?'active':'';?>">
                        <a href="<?php echo $page->getHref() ?>">
                            <?php echo $this->translate($page->getLabel()) ?>
                        </a>
                    </li>
                <?php } else { ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle " data-toggle="dropdown">
                            <?php echo $this->translate($page->getLabel()) ?> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <?php foreach ($page->getPages() as $child) { ?>
                                <?php // when using partials we need to manually check for ACL conditions ?>
                                <?php if(!$child->isVisible() || !$this->navigation()->accept($child)) { continue; } ?>
                                <li class="<?php echo ($child->getActive())?'active':''; ?>" >
                                    <a href="<?php echo $child->getHref() ?>" >
                                        <?php echo $this->translate($child->getLabel()) ?>
                                    </a>
                                </li>
                            <?php } ?>
                        </ul>
                    </li>
                <?php } ?>
            <?php } ?>
            </li>
        </ul>
    </div>

</div>
</nav>
<script type="text/javascript">
	jQuery(document).ready(function($){
		var url = window.location.href;
//		console.log(url);
		url = explode('/', url);
//		console.log(url[3]);
		$('.nav a[href="/'+url[3]+'/"]').parents('.dropdown').addClass('active');
	});
</script>