<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Std\Module'                     => __DIR__ . '/Module.php',
    'Std\Controller\IndexController' => __DIR__ . '/src/Std/Controller/IndexController.php',
    'Std\Controller\Plugin\Head'     => __DIR__ . '/src/Std/Controller/Plugin/Head.php',
    'Std\My\DefaultController'       => __DIR__ . '/src/Std/My/DefaultController.php',
    'Exceptions\DbError'             => __DIR__ . '/src/Std/My/Exceptions/DbError.php',
    'Exceptions\FileNotFound'        => __DIR__ . '/src/Std/My/Exceptions/FileNotFound.php',
    'Exceptions\Http404'             => __DIR__ . '/src/Std/My/Exceptions/Http404.php',
    'Std\Validator\Compare'          => __DIR__ . '/src/Std/Validator/Compare.php',
    'Std\Validator\True'             => __DIR__ . '/src/Std/Validator/True.php',
    'Std\Validator\Unique'           => __DIR__ . '/src/Std/Validator/Unique.php',
);
