<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                                        => __DIR__ . '/Module.php',
    'Application\Controller\IndexController'                    => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Navigation\DefaultBreadcrumbNavigation'        => __DIR__ . '/src/Application/Navigation/DefaultBreadcrumbNavigation.php',
    'Application\Navigation\DefaultBreadcrumbNavigationFactory' => __DIR__ . '/src/Application/Navigation/DefaultBreadcrumbNavigationFactory.php',
    'Application\Navigation\DefaultNavigation'                  => __DIR__ . '/src/Application/Navigation/DefaultNavigation.php',
    'Application\Navigation\DefaultNavigationFactory'           => __DIR__ . '/src/Application/Navigation/DefaultNavigationFactory.php',
);
