<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/std.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
//                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile(
                $this->basePath() . '/js/my/std/my.js',
                'text/javascript'
            )
            ->prependFile(
                $this->basePath() . '/js/my/std/fixes.js',
                'text/javascript'
            )
            ->prependFile(
                $this->basePath() . '/js/my/std/php.js',
                'text/javascript'
            )

            ->prependFile(
                $this->basePath() . '/js/my/vendor/selectivizr-min.js',
                'text/javascript'
            )
            ->prependFile(
                $this->basePath() . '/js/my/vendor/prefixfree.min.js',
                'text/javascript'
            )
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    <div style="color:;">application layout</div>
    <?php
    echo $this->navigation('Application\Navigation\Default')
              ->menu()
              ->setMinDepth(0)
              ->setMaxDepth(0)
              ->setUlClass('nav navbar-nav')
              ->setPartial(array('/partial/topnav.phtml', 'default'));;
    ?>
    <div class="container">
            <?php echo $this->navigation('Application\Navigation\DefaultBreadcrumb')->breadcrumbs()->setMinDepth(0)
                            ->setPartial('/partial/breadcrumb.phtml');
            ?>
            <?php echo $this->content; ?>
            <hr>
            <footer class="text-center">
                <p>&copy; 2015 - <?php echo date('Y') ?> by Ya. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
