<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Tree\Module'                     => __DIR__ . '/Module.php',
    'Tree\Controller\AjaxController'  => __DIR__ . '/src/Tree/Controller/AjaxController.php',
    'Tree\Controller\IndexController' => __DIR__ . '/src/Tree/Controller/IndexController.php',
    'Tree\Document\Ancestor'          => __DIR__ . '/src/Tree/Document/Ancestor.php',
    'Tree\Document\Categories'        => __DIR__ . '/src/Tree/Document/Categories.php',
    'Tree\Document\Project'           => __DIR__ . '/src/Tree/Document/Project.php',
);
