<?php
// module/User/view/user/user/add.phtml:

$this->headTitle( $title );
?>

<div class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title"><?php echo $this->escapeHtml( $title ); ?></h3>
	</div>
	<div class="panel-body">
		<?php
		$form->prepare();
		$form->setAttribute( 'class', 'form-horizontal' );

		echo $this->form()
		          ->openTag( $form );
		echo $this->formHidden( $form->get( 'id' ) );
		?>
		<div class="form-group">
			<?php
			$email = $form->get( 'email' );
			$email->setLabelAttributes( [ 'class' => 'col-lg-2 control-label' ] );
			echo $this->formLabel( $email );
			?>
			<div class="col-lg-10">
				<?php
				$email->setAttribute( 'class', 'form-control' );
				echo $this->formInput( $email );
				echo $this->formElementErrors( $email, [ 'class' => 'red' ] );
				?>
			</div>
		</div>
		<div class="form-group">
			<?php
			$name = $form->get( 'name' );
			$name->setLabelAttributes( [ 'class' => 'col-lg-2 control-label' ] );
			echo $this->formLabel( $name );
			?>
			<div class="col-lg-10">
				<?php
				$name->setAttribute( 'class', 'form-control' );
				echo $this->formInput( $name );
				echo $this->formElementErrors( $name, [ 'class' => 'red' ] );
				?>
			</div>
		</div>
		<div class="form-group">
			<?php
			$last_name = $form->get( 'lastName' );
			$last_name->setLabelAttributes( [ 'class' => 'col-lg-2 control-label' ] );
			echo $this->formLabel( $last_name );
			?>
			<div class="col-lg-10">
				<?php
				$last_name->setAttribute( 'class', 'form-control' );
				echo $this->formInput( $last_name );
				echo $this->formElementErrors( $last_name, [ 'class' => 'red' ] );
				?>
			</div>
		</div>
		<div class="form-group">
			<?php
			$password = $form->get( 'password' );
			$password->setLabelAttributes( [ 'class' => 'col-lg-2 control-label' ] );
			echo $this->formLabel( $password );
			?>
			<div class="col-lg-10">
				<?php
				$password->setAttribute( 'class', 'form-control' );
				echo $this->formInput( $password );
				echo $this->formElementErrors( $password, [ 'class' => 'red' ] );
				?>
			</div>
		</div>
		<div class="form-group">
			<?php
			$confirm_password = $form->get( 'confirmPassword' );
			$confirm_password->setLabelAttributes( [ 'class' => 'col-lg-2 control-label' ] );
			echo $this->formLabel( $confirm_password );
			?>
			<div class="col-lg-10">
				<?php
				$confirm_password->setAttribute( 'class', 'form-control' );
				echo $this->formInput( $confirm_password );
				echo $this->formElementErrors( $confirm_password, [ 'class' => 'red' ] );
				?>
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-10 col-lg-offset-2">
				<?php
				$submit = $form->get( 'submit' );
				$submit->setAttribute( 'class', 'btn btn-info' );
				echo $this->formElement( $submit );
				echo $this->formElementErrors( $submit );
				?>
			</div>
		</div>
		<?php
		echo $this->form()
		          ->closeTag();

		/*
		 * or just
		 * $form->setAttribute('action', $this->url('user', array('action' => 'add')));
		 * $form->prepare();
		 *
		 * echo $this->form()->openTag($form);
		 * echo $this->formCollection($form);
		 * echo $this->form()->closeTag();
		 */
		?>
	</div>
</div>